### ISSUE TITLE
Create streamlit workflow on main branch and PRs

### ISSUE THREAD

**Issue by SammriddhGupta** [SammriddhGupta/chat-pdf#3]
Example main.yml, needs to be edited
Need to create a requirements as well, which needs to be updated oof

```
name: Streamlit App CI

on:
  push:
    branches: [ main ]  # Set the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit  
        pip install -r requirements.txt  # Install other dependencies if needed

    - name: Run Streamlit app
      run: streamlit run app.py  
```
